<?php

namespace App\Services;

use App\Models\User;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ReportingExportService
{
    public function csv(string $report, array $headers, iterable $rows, array $filters, User $user): StreamedResponse
    {
        return response()->streamDownload(function () use ($filters, $headers, $report, $rows, $user): void {
            $output = fopen('php://output', 'w');
            fputcsv($output, ['Report', str($report)->replace('-', ' ')->title()->toString()]);
            fputcsv($output, ['Period', ($filters['date_from'] ?? '').' to '.($filters['date_to'] ?? '')]);
            fputcsv($output, ['Generated At', now()->toIso8601String()]);
            fputcsv($output, ['Generated By', $this->safe($user->name)]);
            fputcsv($output, ['Location Scope', 'SNSU Del Carmen Campus'.($filters['building_id'] ?? null ? ' / Building ID '.$filters['building_id'] : '')]);
            fputcsv($output, ['Applied Filters', json_encode($filters, JSON_UNESCAPED_SLASHES)]);
            fputcsv($output, []);
            fputcsv($output, $headers);
            foreach ($rows as $row) {
                fputcsv($output, array_map(fn (mixed $value): string => $this->safe($value), array_values($row)));
            }
            fclose($output);
        }, 'report-'.$report.'-'.now()->format('Y-m-d').'.csv', ['Content-Type' => 'text/csv']);
    }

    private function safe(mixed $value): string
    {
        $value = (string) ($value ?? '');

        return preg_match('/^[=+\-@\t\r]/', $value) === 1 ? "'{$value}" : $value;
    }
}
