<?php

namespace App\Services;

use App\Models\GeneratedReport;
use App\Models\ReportTemplate;
use App\Models\User;
use Dompdf\Dompdf;
use Dompdf\Options;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Storage;
use Throwable;

class ReportGenerationService
{
    public function __construct(private ReportingService $reports, private ManagementSummaryService $summaries) {}

    public function generate(ReportTemplate $template, array $filters, User $user, ?GeneratedReport $snapshot = null): GeneratedReport
    {
        $snapshot ??= GeneratedReport::create(['report_template_id' => $template->id, 'report_type' => $template->report_type, 'title' => $template->name, 'reporting_period_start' => $filters['date_from'], 'reporting_period_end' => $filters['date_to'], 'filters' => $filters, 'file_format' => $template->output_format, 'generation_status' => 'processing', 'generated_by' => $user->id, 'metadata' => ['template' => $template->only(['uuid', 'name', 'included_sections', 'orientation', 'paper_size'])]]);
        try {
            $data = $this->data($template, $filters);
            $path = 'reports/'.now()->format('Y/m').'/'.$snapshot->uuid;
            $extension = $template->output_format === 'print_view' ? 'html' : $template->output_format;
            $fileName = str($template->slug)->slug().'-'.$snapshot->uuid.'.'.$extension;
            $contents = $this->render($template, $filters, $data, $user);
            Storage::disk(config('reports.disk'))->put("{$path}/{$fileName}", $contents);
            $snapshot->update(['summary_data' => $data['summary'], 'file_path' => "{$path}/{$fileName}", 'file_name' => $fileName, 'generation_status' => 'completed', 'generated_at' => now(), 'checksum' => hash('sha256', $contents), 'metadata' => [...($snapshot->metadata ?? []), 'size' => strlen($contents), 'content_type' => $this->contentType($extension)]]);
        } catch (Throwable $exception) {
            $snapshot->update(['generation_status' => 'failed', 'failure_reason' => str($exception->getMessage())->limit(1000)]);
            throw $exception;
        }

        return $snapshot->fresh(['template', 'generator']);
    }

    public function verify(GeneratedReport $report): bool
    {
        return $report->file_path && Storage::disk(config('reports.disk'))->exists($report->file_path) && hash_equals((string) $report->checksum, hash_file('sha256', Storage::disk(config('reports.disk'))->path($report->file_path)));
    }

    private function data(ReportTemplate $template, array $filters): array
    {
        $dashboard = $this->reports->dashboard($filters);
        $previous = $this->reports->dashboard($this->previousFilters($filters));
        $report = $this->reportSlug($template->report_type);
        $detail = $report ? $this->reports->report($report, [...$filters, 'per_page' => 100]) : null;

        return ['dashboard' => $dashboard, 'detail' => $detail, 'summary' => ['metrics' => $dashboard['metrics'], 'narrative' => $this->summaries->generate($dashboard, $previous)]];
    }

    private function render(ReportTemplate $template, array $filters, array $data, User $user): string
    {
        if ($template->output_format === 'csv') {
            return $this->csv($template, $filters, $data, $user);
        }
        $html = view('admin.reports.print.report', compact('template', 'filters', 'data', 'user'))->render();
        if ($template->output_format === 'print_view') {
            return $html;
        }
        $options = new Options;
        $options->set('isRemoteEnabled', false);
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper($template->paper_size, $template->orientation);
        $dompdf->render();

        return $dompdf->output();
    }

    private function csv(ReportTemplate $template, array $filters, array $data, User $user): string
    {
        $stream = fopen('php://temp', 'w+');
        fputcsv($stream, [$template->name]);
        fputcsv($stream, ['Period', $filters['date_from'].' to '.$filters['date_to']]);
        fputcsv($stream, ['Generated by', $user->name]);
        fputcsv($stream, []);
        foreach ($data['dashboard']['metrics'] as $key => $value) {
            fputcsv($stream, [str($key)->replace('_', ' ')->title(), $value]);
        }
        rewind($stream);

        return stream_get_contents($stream);
    }

    private function previousFilters(array $filters): array
    {
        $from = Carbon::parse($filters['date_from']);
        $to = Carbon::parse($filters['date_to']);
        $days = $from->diffInDays($to) + 1;

        return [...$filters, 'date_from' => $from->copy()->subDays($days)->toDateString(), 'date_to' => $from->copy()->subDay()->toDateString()];
    }

    private function reportSlug(string $type): ?string
    {
        return match ($type) {
            'work_order_summary' => 'work-orders', 'asset_summary', 'building_facility_summary' => 'assets', 'preventive_maintenance_summary' => 'maintenance-schedules', 'maintenance_completion_summary', 'maintenance_review_summary' => 'maintenance-records', 'inventory_summary' => 'inventory', 'staff_workload_summary' => 'staff', default => null
        };
    }

    private function contentType(string $extension): string
    {
        return match ($extension) {
            'pdf' => 'application/pdf', 'csv' => 'text/csv', default => 'text/html'
        };
    }
}
