<x-app-layout>
    <x-slot name="header"><div class="flex w-full flex-wrap items-start justify-between gap-3"><div><p class="text-sm font-medium text-emerald-700">Asset inventory</p><h1 class="text-2xl font-semibold text-gray-900">Assets</h1></div><div class="flex gap-2">@can('export', App\Models\Asset::class)<a href="{{ route('admin.assets.export', request()->query()) }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Export CSV</a>@endcan @can('create', App\Models\Asset::class)<a href="{{ route('admin.assets.create') }}" class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">New asset</a>@endcan</div></div></x-slot>
    <div class="py-6"><div class="mx-auto max-w-7xl space-y-4 px-4 sm:px-6 lg:px-8">
        <form method="GET" class="grid gap-3 rounded-lg border border-gray-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-4">
            <input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search tag, name, brand, model, or serial" class="rounded-md border-gray-300 shadow-sm xl:col-span-2">
            <select name="asset_category_id" class="rounded-md border-gray-300"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)($filters['asset_category_id'] ?? '') === (string)$category->id)>{{ $category->name }}</option>@endforeach</select>
            <select name="status" class="rounded-md border-gray-300"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ str($status)->replace('_', ' ')->title() }}</option>@endforeach</select>
            <select name="building_id" class="rounded-md border-gray-300"><option value="">All buildings</option>@foreach($buildings as $building)<option value="{{ $building->id }}" @selected((string)($filters['building_id'] ?? '') === (string)$building->id)>{{ $building->name }}</option>@endforeach</select>
            <select name="floor_id" class="rounded-md border-gray-300"><option value="">All floors</option>@foreach($floors as $floor)<option value="{{ $floor->id }}" @selected((string)($filters['floor_id'] ?? '') === (string)$floor->id)>{{ $floor->floor_name }}</option>@endforeach</select>
            <select name="room_id" class="rounded-md border-gray-300"><option value="">All rooms</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected((string)($filters['room_id'] ?? '') === (string)$room->id)>{{ $room->room_code }}</option>@endforeach</select>
            <select name="sort" class="rounded-md border-gray-300"><option value="asset_tag">Sort by tag</option><option value="name" @selected(($filters['sort'] ?? '') === 'name')>Sort by name</option><option value="status" @selected(($filters['sort'] ?? '') === 'status')>Sort by status</option><option value="created_at" @selected(($filters['sort'] ?? '') === 'created_at')>Sort by created date</option></select>
            <select name="direction" class="rounded-md border-gray-300"><option value="asc">Ascending</option><option value="desc" @selected(($filters['direction'] ?? '') === 'desc')>Descending</option></select>
            <div class="flex gap-2"><button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Apply</button><a href="{{ route('admin.assets.index') }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Reset</a></div>
        </form>
        <div class="overflow-hidden rounded-md border border-gray-200 bg-white"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Asset</th><th class="px-4 py-3 text-left">Category</th><th class="px-4 py-3 text-left">Location</th><th class="px-4 py-3 text-left">Serial</th><th class="px-4 py-3 text-right">Schedules</th><th class="px-4 py-3 text-right">Completions</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($assets as $asset)<tr><td class="px-4 py-3"><p class="font-semibold text-gray-900">{{ $asset->asset_tag }}</p><p class="text-gray-500">{{ $asset->name }}</p><p class="text-xs text-gray-400">{{ collect([$asset->brand, $asset->model])->filter()->join(' ') }}</p></td><td class="px-4 py-3 text-gray-600">{{ $asset->category?->name ?? 'Uncategorized' }}</td><td class="px-4 py-3 text-gray-600"><p>{{ $asset->location ?? 'Unassigned' }}</p><p class="text-xs text-gray-400">{{ $asset->building?->name }}{{ $asset->room ? ' / '.$asset->room->room_code : '' }}</p></td><td class="px-4 py-3 text-gray-600">{{ $asset->serial_number ?? '-' }}</td><td class="px-4 py-3 text-right text-gray-700">{{ $asset->maintenance_schedules_count }}</td><td class="px-4 py-3 text-right text-gray-700">{{ $asset->maintenance_records_count }}</td><td class="px-4 py-3 text-right"><div class="flex justify-end gap-3"><a href="{{ route('admin.assets.show', $asset) }}" class="font-medium text-emerald-700">View</a>@can('update', $asset)<a href="{{ route('admin.assets.edit', $asset) }}" class="font-medium text-gray-700">Edit</a>@endcan</div></td></tr>@empty<tr><td colspan="7" class="px-4 py-12 text-center text-gray-500">No assets match the current search.</td></tr>@endforelse</tbody></table></div>{{ $assets->links() }}
    </div></div>
</x-app-layout>
