<x-app-layout>
    <x-slot name="header"><div class="flex w-full flex-wrap items-start justify-between gap-3"><div><p class="text-sm font-medium text-emerald-700">{{ $asset->asset_tag }}</p><h1 class="text-2xl font-semibold text-gray-900">{{ $asset->name }}</h1></div><div class="flex gap-2"><a href="{{ route('admin.assets.index') }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Back</a>@can('update', $asset)<a href="{{ route('admin.assets.edit', $asset) }}" class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Edit</a>@endcan</div></div></x-slot>
    <div class="py-6"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <section class="grid gap-4 rounded-lg border border-gray-200 bg-white p-5 shadow-sm md:grid-cols-4"><div><p class="text-xs font-semibold uppercase text-gray-500">Category</p><p class="mt-1 font-medium text-gray-900">{{ $asset->category?->name ?? 'Uncategorized' }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Location</p><p class="mt-1 font-medium text-gray-900">{{ $asset->location ?? 'Unassigned' }}</p><p class="text-xs text-gray-500">{{ collect([$asset->building?->name, $asset->floor?->floor_name, $asset->room?->room_code])->filter()->join(' / ') }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Status</p><p class="mt-1 font-medium text-gray-900">{{ str($asset->status)->replace('_', ' ')->title() }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Schedules / History</p><p class="mt-1 font-medium text-gray-900">{{ $asset->maintenanceSchedules->count() }} / {{ $records->total() }}</p></div></section>
        <section class="grid gap-4 rounded-lg border border-gray-200 bg-white p-5 shadow-sm md:grid-cols-4"><div><p class="text-xs font-semibold uppercase text-gray-500">Brand</p><p class="mt-1 font-medium text-gray-900">{{ $asset->brand ?? '-' }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Model</p><p class="mt-1 font-medium text-gray-900">{{ $asset->model ?? '-' }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Serial number</p><p class="mt-1 font-medium text-gray-900">{{ $asset->serial_number ?? '-' }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Warranty until</p><p class="mt-1 font-medium text-gray-900">{{ $asset->warranty_until?->toFormattedDateString() ?? '-' }}</p></div></section>
        @if($asset->remarks)<section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-semibold text-gray-900">Remarks</h2><p class="mt-2 text-sm text-gray-700">{{ $asset->remarks }}</p></section>@endif
        <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 class="text-lg font-semibold text-gray-900">Photos</h2></div><div class="grid gap-3 md:grid-cols-3">@forelse($asset->photos as $photo)<div class="rounded-md border border-gray-200 p-3 text-sm"><p class="font-medium text-gray-900">{{ $photo->caption ?? $photo->original_name ?? 'Asset photo' }}</p><p class="mt-1 break-all text-gray-500">{{ $photo->image_path }}</p><p class="mt-1 text-xs text-gray-400">{{ $photo->mime_type }} {{ $photo->size ? ' / '.$photo->size.' bytes' : '' }}</p></div>@empty<p class="text-sm text-gray-500">No photo metadata has been added.</p>@endforelse</div>@can('update', $asset)<form method="POST" action="{{ route('admin.assets.photos.store', $asset) }}" class="mt-4 grid gap-3 md:grid-cols-5">@csrf<input name="image_path" placeholder="Image path" class="rounded-md border-gray-300 shadow-sm md:col-span-2"><input name="caption" placeholder="Caption" class="rounded-md border-gray-300 shadow-sm"><input name="original_name" placeholder="Original file name" class="rounded-md border-gray-300 shadow-sm"><button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Add photo</button></form>@endcan</section>
        <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold text-gray-900">Maintenance history</h2><p class="mt-1 text-sm text-gray-500">Timeline of completed maintenance tied to this asset.</p></div><a href="{{ route('admin.asset-maintenance.export', ['asset_id' => $asset->id]) }}" class="text-sm font-semibold text-gray-700">Export CSV</a></div><div class="space-y-3">@forelse($records as $record)<a href="{{ route('admin.asset-maintenance.show', $record) }}" class="block rounded-md border border-gray-200 p-4 hover:bg-gray-50"><div class="flex items-start justify-between gap-4"><div><p class="font-semibold text-gray-900">{{ $record->completion_date?->toFormattedDateString() }}</p><p class="text-sm text-gray-600">{{ $record->actions_taken }}</p><p class="mt-1 text-xs text-gray-500">{{ $record->maintenanceSchedule?->title }} {{ $record->workOrder?->work_order_number ? ' / '.$record->workOrder->work_order_number : '' }}</p></div><span class="text-sm text-gray-500">{{ $record->staffProfile?->user?->name ?? $record->completedBy?->name }}</span></div></a>@empty<p class="text-sm text-gray-500">No completed maintenance records yet.</p>@endforelse</div><div class="mt-4">{{ $records->links() }}</div></section>
    </div></div>
</x-app-layout>
