<x-app-layout>
    <x-slot name="header"><div class="flex w-full items-center justify-between gap-4"><div><p class="text-sm font-medium text-emerald-700">Asset {{ $asset->asset_tag }}</p><h1 class="text-2xl font-semibold text-gray-900">{{ $asset->name }}</h1></div><a href="{{ route('admin.asset-maintenance.create', ['asset_id' => $asset->id]) }}" class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Record completion</a></div></x-slot>
    <div class="space-y-7">
        <section class="grid gap-4 rounded-lg border border-gray-200 bg-white p-5 shadow-sm md:grid-cols-4"><div><p class="text-xs font-semibold uppercase text-gray-500">Location</p><p class="mt-1 font-medium text-gray-900">{{ $asset->location ?? 'Unassigned' }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Status</p><p class="mt-1 font-medium text-gray-900">{{ ucfirst($asset->status) }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">Schedules</p><p class="mt-1 font-medium text-gray-900">{{ $asset->maintenanceSchedules->count() }}</p></div><div><p class="text-xs font-semibold uppercase text-gray-500">History records</p><p class="mt-1 font-medium text-gray-900">{{ $records->total() }}</p></div></section>
        <section>
            <div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold text-gray-900">Maintenance history</h2><p class="mt-1 text-sm text-gray-500">Timeline of completed maintenance tied to this asset.</p></div><a href="{{ route('admin.asset-maintenance.export', ['asset_id' => $asset->id]) }}" class="text-sm font-semibold text-gray-700">Export CSV</a></div>
            <div class="overflow-hidden rounded-md border border-gray-200 bg-white"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Date</th><th class="px-4 py-3 text-left">Technician</th><th class="px-4 py-3 text-left">Source</th><th class="px-4 py-3 text-left">Actions taken</th><th class="px-4 py-3 text-right">Labor</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($records as $record)<tr><td class="px-4 py-3 font-medium text-gray-900"><a href="{{ route('admin.asset-maintenance.show', $record) }}">{{ $record->completion_date->format('M j, Y') }}</a></td><td class="px-4 py-3 text-gray-600">{{ $record->staffProfile?->user?->name ?? 'Not assigned' }}</td><td class="px-4 py-3 text-gray-600">{{ $record->maintenanceSchedule?->title ?? $record->workOrder?->work_order_number ?? 'Manual' }}</td><td class="px-4 py-3 text-gray-700">{{ str($record->actions_taken)->limit(90) }}</td><td class="px-4 py-3 text-right text-gray-700">{{ $record->labor_cost ? number_format((float) $record->labor_cost, 2) : '-' }}</td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-gray-500">No maintenance completion history yet.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}
        </section>
    </div>
</x-app-layout>
