import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../app/providers.dart';
import '../../core/network/api_error.dart';
import '../../data/models/user.dart';
import '../../shared/widgets.dart';

class ProfileScreen extends ConsumerStatefulWidget{const ProfileScreen({super.key});@override ConsumerState<ProfileScreen>createState()=>_ProfileState();}
class _ProfileState extends ConsumerState<ProfileScreen>{AppUser? user;Object? error;@override void initState(){super.initState();_load();}Future<void>_load()async{try{final v=await ref.read(profileRepositoryProvider).load();if(mounted)setState(()=>user=v);}catch(e){if(mounted)setState(()=>error=e);}}Future<void>_password()async{final current=TextEditingController(),password=TextEditingController(),confirm=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Change password'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:current,obscureText:true,decoration:const InputDecoration(labelText:'Current password')),const SizedBox(height:10),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'New password')),const SizedBox(height:10),TextField(controller:confirm,obscureText:true,decoration:const InputDecoration(labelText:'Confirm new password'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Change'))]));if(ok!=true||!mounted)return;try{await ref.read(profileRepositoryProvider).password({'current_password':current.text,'password':password.text,'password_confirmation':confirm.text});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Password changed. Other sessions were revoked.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ApiError.messageFor(e))));}}
 Future<void>_edit()async{final email=TextEditingController(text:user!.email),mobile=TextEditingController(text:user!.mobileNumber);final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Edit profile'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email')),const SizedBox(height:10),TextField(controller:mobile,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Mobile number'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))]));if(ok!=true||!mounted)return;try{final updated=await ref.read(profileRepositoryProvider).update({'email':email.text.trim(),'mobile_number':mobile.text.trim()});if(mounted)setState(()=>user=updated);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ApiError.messageFor(e))));}}
 @override Widget build(BuildContext c){if(error!=null)return ErrorPanel(ApiError.messageFor(error),onRetry:_load);if(user==null)return const LoadingPanel();final u=user!;return ListView(padding:const EdgeInsets.all(16),children:[CircleAvatar(radius:36,child:Text(u.name.isEmpty?'?':u.name.characters.first.toUpperCase())),const SizedBox(height:12),Text(u.name,textAlign:TextAlign.center,style:Theme.of(c).textTheme.headlineSmall),Text(u.email,textAlign:TextAlign.center),const SizedBox(height:24),DetailSection(title:'Account',children:[LabeledValue('Mobile',u.mobileNumber??'Not provided'),LabeledValue('Roles',u.roles.isEmpty?'None':u.roles.join(', ')),LabeledValue('Permissions','${u.permissions.length} granted')]),OutlinedButton.icon(onPressed:_edit,icon:const Icon(Icons.edit_outlined),label:const Text('Edit profile')),const SizedBox(height:8),OutlinedButton.icon(onPressed:_password,icon:const Icon(Icons.password),label:const Text('Change password')),const SizedBox(height:8),FilledButton.icon(onPressed:()=>ref.read(authControllerProvider.notifier).logout(),icon:const Icon(Icons.logout),label:const Text('Sign out')),TextButton(onPressed:()=>ref.read(authControllerProvider.notifier).logout(all:true),child:const Text('Sign out all devices'))]);}}
