import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';

import '../../app/providers.dart';
import '../../core/network/api_error.dart';
import '../../data/models/maintenance.dart';
import '../../shared/widgets.dart';

class MaintenanceListScreen extends ConsumerStatefulWidget{const MaintenanceListScreen({super.key});@override ConsumerState<MaintenanceListScreen>createState()=>_MaintenanceListState();}
class _MaintenanceListState extends ConsumerState<MaintenanceListScreen>with SingleTickerProviderStateMixin{late final TabController tabs;List<MaintenanceSchedule>? schedules;Object? error;@override void initState(){super.initState();tabs=TabController(length:2,vsync:this)..addListener(_tab);_load();}@override void dispose(){tabs.dispose();super.dispose();}void _tab(){if(!tabs.indexIsChanging)_load();}Future<void>_load()async{setState((){schedules=null;error=null;});try{final v=await ref.read(maintenanceRepositoryProvider).schedules(overdue:tabs.index==1);if(mounted)setState(()=>schedules=v);}catch(e){if(mounted)setState(()=>error=e);}}@override Widget build(BuildContext c)=>Column(children:[TabBar(controller:tabs,tabs:const[Tab(text:'Upcoming'),Tab(text:'Overdue')]),Expanded(child:error!=null?ErrorPanel(ApiError.messageFor(error),onRetry:_load):schedules==null?const LoadingPanel():RefreshIndicator(onRefresh:_load,child:schedules!.isEmpty?ListView(children:[SizedBox(height:MediaQuery.sizeOf(c).height*.5,child:const EmptyPanel('No maintenance schedules in this view.'))]):ListView.builder(itemCount:schedules!.length,itemBuilder:(c,i){final s=schedules![i];return ListTile(leading:Icon(tabs.index==1?Icons.warning_amber:Icons.event_available_outlined),title:Text(s.title),subtitle:Text('${s.assetCode??'Asset'} · ${s.frequency}\nDue ${DateFormat.yMMMd().format(s.nextDueDate.toLocal())}'),isThreeLine:true,onTap:()=>c.push('/maintenance/${s.uuid}'));})))]) ;}

class MaintenanceDetailScreen extends ConsumerStatefulWidget{const MaintenanceDetailScreen(this.uuid,{super.key});final String uuid;@override ConsumerState<MaintenanceDetailScreen>createState()=>_MaintenanceDetailState();}
class _MaintenanceDetailState extends ConsumerState<MaintenanceDetailScreen>{MaintenanceSchedule? schedule;Object? error;bool submitting=false;@override void initState(){super.initState();_load();}Future<void>_load()async{try{final v=await ref.read(maintenanceRepositoryProvider).detail(widget.uuid);if(mounted)setState(()=>schedule=v);}catch(e){if(mounted)setState(()=>error=e);}}Future<void>_complete()async{final actions=TextEditingController();final findings=TextEditingController();final accepted=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Complete maintenance'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:actions,maxLines:3,decoration:const InputDecoration(labelText:'Actions taken')),const SizedBox(height:12),TextField(controller:findings,maxLines:3,decoration:const InputDecoration(labelText:'Findings (optional)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Submit'))]));if(accepted!=true||actions.text.trim().isEmpty||!mounted)return;setState(()=>submitting=true);try{await ref.read(maintenanceRepositoryProvider).complete(widget.uuid,{'completion_date':DateFormat('yyyy-MM-dd').format(DateTime.now()),'actions_taken':actions.text.trim(),'findings':findings.text.trim()});await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ApiError.messageFor(e))));}finally{if(mounted)setState(()=>submitting=false);}}
 @override Widget build(BuildContext c){if(error!=null)return ErrorPanel(ApiError.messageFor(error),onRetry:_load);if(schedule==null)return const LoadingPanel();final s=schedule!;final canComplete=(ref.watch(authControllerProvider).user?.canCompleteMaintenance??false)&&(ref.watch(authControllerProvider).systemInfo?.enabled('mobile_maintenance_completion')??false);return RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[Text(s.assetCode??'Asset',style:Theme.of(c).textTheme.labelLarge),Text(s.title,style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:20),DetailSection(title:'Schedule',children:[LabeledValue('Frequency',s.frequency),LabeledValue('Next due',DateFormat.yMMMd().format(s.nextDueDate.toLocal())),LabeledValue('Last completed',s.lastCompletedDate==null?'Never':DateFormat.yMMMd().format(s.lastCompletedDate!.toLocal()))]),if(canComplete)FilledButton.icon(onPressed:submitting?null:_complete,icon:const Icon(Icons.task_alt),label:const Text('Record completion')),const SizedBox(height:20),const DetailSection(title:'Review workflow',children:[Text('Completion records remain subject to the server-managed maintenance review workflow.')])])) ;}}
