<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-medium text-emerald-700">Administration / Access</p><h1 class="text-2xl font-semibold text-gray-900">Permissions</h1></div></x-slot>
    <div class="space-y-5">@include('admin.partials.tabs')
        <div class="rounded-md border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">Permission keys are system-managed because policies reference their exact names. Assign them through roles rather than renaming them.</div>
        <form method="GET" class="grid gap-3 border-b border-gray-200 pb-5 sm:grid-cols-[1fr_11rem_9rem_auto]"><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search permissions" aria-label="Search permissions" class="rounded-md border-gray-300 text-sm"><select name="sort" aria-label="Sort permissions" class="rounded-md border-gray-300 text-sm"><option value="name">Name</option><option value="created_at" @selected(($filters['sort'] ?? '')==='created_at')>Created date</option></select><select name="per_page" aria-label="Rows per page" class="rounded-md border-gray-300 text-sm">@foreach([10,15,25,50] as $number)<option value="{{ $number }}" @selected((int)($filters['per_page'] ?? 15)===$number)>{{ $number }} rows</option>@endforeach</select><button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Apply</button></form>
        <div class="flex justify-between"><p class="text-sm text-gray-500">{{ $permissions->total() }} permissions</p><a href="{{ route('admin.permissions.export', request()->query()) }}" class="text-sm font-semibold text-gray-700">Export CSV</a></div>
        <div class="overflow-hidden rounded-md border border-gray-200 bg-white"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Permission</th><th class="px-4 py-3 text-left">Roles</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($permissions as $permission)<tr><td class="px-4 py-3"><p class="font-semibold">{{ Str::headline($permission->name) }}</p><code class="text-xs text-gray-500">{{ $permission->name }}</code></td><td class="px-4 py-3 text-gray-600">{{ $permission->roles_count }}</td><td class="px-4 py-3 text-right"><a href="{{ route('admin.permissions.show', $permission) }}" class="font-medium text-emerald-700">View</a></td></tr>@empty<tr><td colspan="3" class="px-4 py-12 text-center text-gray-500">No permissions match the current search.</td></tr>@endforelse</tbody></table></div>{{ $permissions->links() }}
    </div>
</x-app-layout>
