<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-medium text-emerald-700">Administration / Staff</p><h1 class="text-2xl font-semibold text-gray-900">{{ $profile ? 'Edit staff profile' : 'Add staff profile' }}</h1></div></x-slot>
    <div class="mx-auto max-w-4xl space-y-5">@include('admin.partials.tabs')
        <form method="POST" action="{{ $profile ? route('admin.staff.update', $profile) : route('admin.staff.store') }}" class="space-y-6 rounded-md border border-gray-200 bg-white p-6">@csrf @if($profile)@method('PUT')@endif
            <div class="grid gap-5 sm:grid-cols-2">
                <div><label for="user_id" class="mb-1 block text-sm font-medium">User account</label><select id="user_id" name="user_id" class="w-full rounded-md border-gray-300 text-sm"><option value="">Select user</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)old('user_id', $profile?->user_id) === (string)$user->id)>{{ $user->name }} · {{ $user->email }}</option>@endforeach</select>@error('user_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
                @foreach(['employee_code'=>'Employee code','position'=>'Position','designation'=>'Designation'] as $name=>$label)<div><label for="{{ $name }}" class="mb-1 block text-sm font-medium">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" value="{{ old($name, $profile?->{$name}) }}" class="w-full rounded-md border-gray-300 text-sm">@error($name)<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
                <div><label for="employment_status" class="mb-1 block text-sm font-medium">Employment status</label><select id="employment_status" name="employment_status" class="w-full rounded-md border-gray-300 text-sm">@foreach(['active','inactive','contractual','on_leave'] as $value)<option value="{{ $value }}" @selected(old('employment_status', $profile?->employment_status ?? 'active') === $value)>{{ Str::headline($value) }}</option>@endforeach</select></div>
                <div><label for="availability_status" class="mb-1 block text-sm font-medium">Availability</label><select id="availability_status" name="availability_status" class="w-full rounded-md border-gray-300 text-sm">@foreach(['available','busy','unavailable','on_leave'] as $value)<option value="{{ $value }}" @selected(old('availability_status', $profile?->availability_status ?? 'available') === $value)>{{ Str::headline($value) }}</option>@endforeach</select></div>
                <div class="sm:col-span-2"><label for="remarks" class="mb-1 block text-sm font-medium">Remarks</label><textarea id="remarks" name="remarks" rows="3" class="w-full rounded-md border-gray-300 text-sm">{{ old('remarks', $profile?->remarks) }}</textarea></div>
            </div>
            <input type="hidden" name="skills_present" value="1"><fieldset><legend class="mb-3 text-sm font-semibold">Skills</legend><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@forelse($skills as $skill)<label class="flex items-center gap-2 rounded-md border border-gray-200 px-3 py-2 text-sm"><input type="checkbox" name="skill_ids[]" value="{{ $skill->id }}" @checked(in_array($skill->id, old('skill_ids', $profile?->skills->pluck('id')->all() ?? []), true)) class="rounded border-gray-300 text-emerald-700">{{ $skill->name }}</label>@empty<p class="text-sm text-gray-500">No active skills are available.</p>@endforelse</div></fieldset>
            <div class="flex justify-end gap-3 border-t border-gray-200 pt-5"><a href="{{ route('admin.staff.index') }}" class="px-3 py-2 text-sm font-semibold text-gray-600">Cancel</a><button class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">{{ $profile ? 'Save changes' : 'Create profile' }}</button></div>
        </form>
    </div>
</x-app-layout>
