<x-app-layout>
    <x-slot name="header"><div class="flex w-full items-center justify-between gap-4"><div><p class="text-sm font-medium text-emerald-700">Administration / Staff</p><h1 class="text-2xl font-semibold text-gray-900">Staff profiles</h1></div><a href="{{ route('admin.staff.create') }}" class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Add profile</a></div></x-slot>
    <div class="space-y-5">
        @if(session('success'))<div class="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
        @include('admin.partials.tabs')
        <form method="GET" class="grid gap-3 border-b border-gray-200 pb-5 sm:grid-cols-2 xl:grid-cols-[1fr_10rem_11rem_11rem_9rem_auto]">
            <input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search staff" aria-label="Search staff" class="rounded-md border-gray-300 text-sm">
            <select name="availability" aria-label="Availability filter" class="rounded-md border-gray-300 text-sm"><option value="">All availability</option>@foreach(['available','busy','unavailable','on_leave'] as $value)<option value="{{ $value }}" @selected(($filters['availability'] ?? '') === $value)>{{ Str::headline($value) }}</option>@endforeach</select>
            <select name="status" aria-label="Employment filter" class="rounded-md border-gray-300 text-sm"><option value="">All employment</option>@foreach(['active','inactive','contractual','on_leave'] as $value)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ Str::headline($value) }}</option>@endforeach</select>
            <select name="skill" aria-label="Skill filter" class="rounded-md border-gray-300 text-sm"><option value="">All skills</option>@foreach($skills as $skill)<option value="{{ $skill->name }}" @selected(($filters['skill'] ?? '') === $skill->name)>{{ $skill->name }}</option>@endforeach</select>
            <select name="per_page" aria-label="Rows per page" class="rounded-md border-gray-300 text-sm">@foreach([10,15,25,50] as $number)<option value="{{ $number }}" @selected((int)($filters['per_page'] ?? 15) === $number)>{{ $number }} rows</option>@endforeach</select>
            <button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Apply</button>
        </form>
        <div class="flex justify-between gap-4"><p class="text-sm text-gray-500">{{ $profiles->total() }} staff profiles</p><a href="{{ route('admin.staff.export', request()->query()) }}" class="text-sm font-semibold text-gray-700 hover:text-emerald-700">Export CSV</a></div>
        <div class="overflow-hidden rounded-md border border-gray-200 bg-white"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm">
            <thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Staff member</th><th class="px-4 py-3 text-left">Position</th><th class="px-4 py-3 text-left">Availability</th><th class="px-4 py-3 text-left">Skills</th><th class="px-4 py-3 text-right">Actions</th></tr></thead>
            <tbody class="divide-y divide-gray-100">@forelse($profiles as $profile)<tr class="hover:bg-gray-50"><td class="px-4 py-3"><p class="font-semibold text-gray-900">{{ $profile->user?->name }}</p><p class="text-gray-500">{{ $profile->employee_code }}</p></td><td class="px-4 py-3"><p>{{ $profile->position ?: '—' }}</p><p class="text-xs text-gray-500">{{ Str::headline($profile->employment_status) }}</p></td><td class="px-4 py-3"><span class="rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-700">{{ Str::headline($profile->availability_status) }}</span></td><td class="max-w-xs px-4 py-3 text-gray-600">{{ $profile->skills->pluck('name')->implode(', ') ?: 'No skills assigned' }}</td><td class="whitespace-nowrap px-4 py-3 text-right"><a href="{{ route('admin.staff.show', $profile) }}" class="font-medium text-gray-600">View</a><a href="{{ route('admin.staff.edit', $profile) }}" class="ml-3 font-medium text-emerald-700">Edit</a><a href="{{ route('admin.staff.skills.edit', $profile) }}" class="ml-3 font-medium text-emerald-700">Skills</a></td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-gray-500">No staff profiles match the current filters.</td></tr>@endforelse</tbody>
        </table></div></div>
        {{ $profiles->links() }}
    </div>
</x-app-layout>
