<?php

namespace App\Http\Controllers\Web\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Kpi\SaveKpiTargetRequest;
use App\Models\KpiCorrectiveAction;
use App\Models\KpiDefinition;
use App\Models\KpiTarget;
use App\Models\User;
use App\Services\KpiEvaluationService;
use App\Services\KpiScorecardService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\View\View;

class KpiController extends Controller
{
    public function scorecard(Request $r, KpiScorecardService $s): View
    {
        Gate::authorize('viewAny', KpiTarget::class);

        return view('admin.kpi.scorecard', ['scorecard' => $s->build($r->only(['category', 'owner_user_id']))]);
    }

    public function definitions(): View
    {
        Gate::authorize('viewAny', KpiDefinition::class);

        return view('admin.kpi.definitions', ['definitions' => KpiDefinition::orderBy('category')->orderBy('name')->paginate(25)]);
    }

    public function targets(Request $r): View
    {
        Gate::authorize('viewAny', KpiTarget::class);
        $q = KpiTarget::with(['definition', 'owner', 'evaluations'])->latest();
        if (! $r->user()->can('manage_kpi_targets')) {
            $q->where('owner_user_id', $r->user()->id);
        }

        return view('admin.kpi.targets', ['targets' => $q->paginate(20)]);
    }

    public function create(): View
    {
        Gate::authorize('create', KpiTarget::class);

        return view('admin.kpi.target-form', ['target' => null, 'definitions' => KpiDefinition::where('is_active', true)->get(), 'users' => User::where('is_active', true)->orderBy('name')->get()]);
    }

    public function store(SaveKpiTargetRequest $r): RedirectResponse
    {
        $t = KpiTarget::create([...$r->validated(), 'created_by' => $r->user()->id]);

        return redirect()->route('admin.kpi-targets.show', $t)->with('status', 'KPI target created.');
    }

    public function show(KpiTarget $kpiTarget): View
    {
        Gate::authorize('view', $kpiTarget);

        return view('admin.kpi.target-show', ['target' => $kpiTarget->load(['definition', 'owner', 'evaluations', 'correctiveActions.assignee'])]);
    }

    public function evaluate(KpiTarget $kpiTarget, Request $r, KpiEvaluationService $s): RedirectResponse
    {
        Gate::authorize('evaluate', $kpiTarget);
        $s->evaluate($kpiTarget, $r->user()->id);

        return back()->with('status', 'KPI evaluation recorded.');
    }

    public function actions(Request $r): View
    {
        Gate::authorize('viewAny', KpiCorrectiveAction::class);
        $q = KpiCorrectiveAction::with(['target.definition', 'assignee'])->latest();
        if (! $r->user()->can('manage_kpi_corrective_actions')) {
            $q->where('assigned_to', $r->user()->id);
        }

        return view('admin.kpi.actions', ['actions' => $q->paginate(20)]);
    }

    public function export(Request $r, KpiScorecardService $s)
    {
        Gate::authorize('viewAny', KpiTarget::class);
        $data = $s->build($r->only(['category', 'owner_user_id']));

        return response()->streamDownload(function () use ($data, $r) {
            $o = fopen('php://output', 'w');
            fputcsv($o, ['KPI Scorecard']);
            fputcsv($o, ['Generated by', $r->user()->name]);
            fputcsv($o, ['Generated at', now()->toIso8601String()]);
            fputcsv($o, []);
            fputcsv($o, ['KPI', 'Target', 'Actual', 'Variance', 'Score', 'Status', 'Trend', 'Owner']);
            foreach ($data['rows'] as $row) {
                $t = $row['target'];
                $e = $row['evaluation'];
                fputcsv($o, [$t->definition->name, $t->target_value, $e?->actual_value, $e?->variance, $e?->score, $row['status'], $e?->trend_direction, $t->owner?->name]);
            }fclose($o);
        }, 'kpi-scorecard-'.today()->toDateString().'.csv', ['Content-Type' => 'text/csv']);
    }
}
