<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-medium text-emerald-700">Administration / Inventory</p><h1 class="text-2xl font-semibold text-gray-900">{{ $item ? 'Edit item' : 'Add item' }}</h1></div></x-slot>
    <div class="mx-auto max-w-3xl"><form method="POST" action="{{ $item ? route('admin.inventory.update', $item) : route('admin.inventory.store') }}" class="space-y-5 rounded-md border border-gray-200 bg-white p-6">@csrf @if($item)@method('PUT')@endif
        <div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1 block text-sm font-medium">Item code</label><input name="item_code" value="{{ old('item_code', $item?->item_code) }}" class="w-full rounded-md border-gray-300 text-sm">@error('item_code')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-medium">Category</label><select name="category_id" class="w-full rounded-md border-gray-300 text-sm"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id', $item?->category_id) === (string)$category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div></div>
        <div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1 block text-sm font-medium">Name</label><input name="name" value="{{ old('name', $item?->name) }}" class="w-full rounded-md border-gray-300 text-sm">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-medium">Brand</label><input name="brand" value="{{ old('brand', $item?->brand) }}" class="w-full rounded-md border-gray-300 text-sm"></div></div>
        <div class="grid gap-4 sm:grid-cols-3"><div><label class="mb-1 block text-sm font-medium">Unit</label><input name="unit" value="{{ old('unit', $item?->unit) }}" class="w-full rounded-md border-gray-300 text-sm">@error('unit')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-medium">Minimum stock</label><input name="minimum_stock" type="number" step="0.01" min="0" value="{{ old('minimum_stock', $item?->minimum_stock ?? 0) }}" class="w-full rounded-md border-gray-300 text-sm"></div>@if(! $item)<div><label class="mb-1 block text-sm font-medium">Initial stock</label><input name="current_stock" type="number" step="0.01" min="0" value="{{ old('current_stock', 0) }}" class="w-full rounded-md border-gray-300 text-sm"></div>@endif</div>
        <div><label class="mb-1 block text-sm font-medium">Remarks</label><textarea name="remarks" rows="4" class="w-full rounded-md border-gray-300 text-sm">{{ old('remarks', $item?->remarks) }}</textarea></div><div><label class="mb-1 block text-sm font-medium">Status</label><select name="status" class="w-full rounded-md border-gray-300 text-sm"><option value="active" @selected(old('status', $item?->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $item?->status) === 'inactive')>Inactive</option></select></div>
        <div class="flex justify-end gap-3 border-t border-gray-200 pt-5"><a href="{{ $item ? route('admin.inventory.show', $item) : route('admin.inventory.index') }}" class="px-3 py-2 text-sm font-semibold text-gray-600">Cancel</a><button class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">{{ $item ? 'Save changes' : 'Create item' }}</button></div>
    </form></div>
</x-app-layout>