<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-medium text-emerald-700">Maintenance review</p><h1 class="text-2xl font-semibold text-gray-900">Correct maintenance record</h1></div></x-slot>
    <form method="POST" action="{{ route('admin.maintenance-reviews.correction.update', $record) }}" class="space-y-5 rounded-md border border-gray-200 bg-white p-6 shadow-sm">@csrf @method('PATCH')
        <div class="rounded-md border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Correction requested:</strong> {{ $record->correction_reason }}</div>
        <div class="grid gap-4 md:grid-cols-2"><label class="grid gap-2 text-sm font-medium text-gray-700">Maintenance type<select name="maintenance_type_id" class="rounded-md border-gray-300"><option value="">Not specified</option>@foreach($maintenanceTypes as $type)<option value="{{ $type->id }}" @selected((string)old('maintenance_type_id', $record->maintenance_type_id) === (string)$type->id)>{{ $type->name }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-medium text-gray-700">Maintenance date<input type="date" name="maintenance_date" value="{{ old('maintenance_date', $record->maintenance_date?->toDateString()) }}" required class="rounded-md border-gray-300"></label><label class="grid gap-2 text-sm font-medium text-gray-700">Performed by<input name="performed_by" value="{{ old('performed_by', $record->performed_by) }}" class="rounded-md border-gray-300"></label><label class="grid gap-2 text-sm font-medium text-gray-700">Next maintenance<input type="date" name="next_maintenance_date" value="{{ old('next_maintenance_date', $record->next_maintenance_date?->toDateString()) }}" class="rounded-md border-gray-300"></label><label class="grid gap-2 text-sm font-medium text-gray-700">Labor cost<input type="number" step="0.01" min="0" name="labor_cost" value="{{ old('labor_cost', $record->labor_cost) }}" class="rounded-md border-gray-300"></label><label class="grid gap-2 text-sm font-medium text-gray-700">Total cost<input type="number" step="0.01" min="0" name="total_cost" value="{{ old('total_cost', $record->total_cost) }}" class="rounded-md border-gray-300"></label></div>
        <label class="grid gap-2 text-sm font-medium text-gray-700">Findings<textarea name="findings" rows="3" class="rounded-md border-gray-300">{{ old('findings', $record->findings) }}</textarea></label><label class="grid gap-2 text-sm font-medium text-gray-700">Actions taken<textarea name="actions_taken" rows="4" required class="rounded-md border-gray-300">{{ old('actions_taken', $record->actions_taken) }}</textarea></label><label class="grid gap-2 text-sm font-medium text-gray-700">Remarks<textarea name="remarks" rows="3" class="rounded-md border-gray-300">{{ old('remarks', $record->remarks) }}</textarea></label><label class="grid gap-2 text-sm font-medium text-gray-700">Correction notes<textarea name="correction_notes" rows="3" class="rounded-md border-gray-300">{{ old('correction_notes') }}</textarea></label>
        <div class="flex justify-end gap-3"><a href="{{ route('admin.maintenance-reviews.show', $record) }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Cancel</a><button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Save correction</button></div>
    </form>
</x-app-layout>
