<x-app-layout>
    <x-slot name="header"><div class="flex items-start justify-between gap-4"><div><p class="text-sm font-medium text-emerald-700">{{ $record->asset?->asset_tag }}</p><h1 class="text-2xl font-semibold text-gray-900">Maintenance review</h1></div><span class="rounded-md bg-gray-100 px-3 py-2 text-sm font-semibold text-gray-700">{{ str($record->review_status)->replace('_', ' ')->title() }}</span></div></x-slot>

    @if(session('success'))<div class="mb-5 rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
        <div class="space-y-5">
            <section class="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Maintenance details</h2><dl class="mt-4 grid gap-4 text-sm md:grid-cols-2"><div><dt class="text-gray-500">Asset</dt><dd class="font-medium">{{ $record->asset?->asset_tag }} - {{ $record->asset?->name }}</dd></div><div><dt class="text-gray-500">Maintenance date</dt><dd class="font-medium">{{ $record->maintenance_date?->toFormattedDateString() }}</dd></div><div><dt class="text-gray-500">Schedule</dt><dd class="font-medium">{{ $record->maintenanceSchedule?->title ?? 'Unscheduled' }}</dd></div><div><dt class="text-gray-500">Work order</dt><dd class="font-medium">{{ $record->workOrder?->work_order_number ?? 'Not linked' }}</dd></div><div><dt class="text-gray-500">Technician</dt><dd class="font-medium">{{ $record->staffProfile?->user?->name ?? $record->performed_by ?? 'Not recorded' }}</dd></div><div><dt class="text-gray-500">Labor / Total cost</dt><dd class="font-medium">{{ $record->labor_cost ?? '-' }} / {{ $record->total_cost ?? '-' }}</dd></div></dl></section>
            @foreach(['findings' => 'Findings', 'actions_taken' => 'Actions taken', 'remarks' => 'Remarks'] as $field => $label)@if($record->{$field})<section class="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">{{ $label }}</h2><p class="mt-3 whitespace-pre-line text-sm leading-6 text-gray-700">{{ $record->{$field} }}</p></section>@endif @endforeach
            <section class="rounded-md border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Review timeline</h2><div class="mt-4 space-y-4">@forelse($record->reviewActions as $action)<div class="border-l-2 border-emerald-200 pl-4"><div class="flex justify-between gap-4"><p class="font-medium text-gray-900">{{ str($action->action)->replace('_', ' ')->title() }}</p><time class="text-xs text-gray-500">{{ $action->acted_at?->format('M j, Y g:i A') }}</time></div><p class="text-sm text-gray-500">{{ $action->actor?->name ?? 'System' }} · {{ str($action->previous_status)->replace('_', ' ') }} → {{ str($action->new_status)->replace('_', ' ') }}</p>@if($action->comments)<p class="mt-1 text-sm text-gray-700">{{ $action->comments }}</p>@endif</div>@empty<p class="text-sm text-gray-500">No review actions recorded.</p>@endforelse</div></section>
        </div>

        <aside class="space-y-4">
            @can('approve', $record)<form method="POST" action="{{ route('admin.maintenance-reviews.approve', $record) }}" class="space-y-3 rounded-md border border-gray-200 bg-white p-4">@csrf<label class="grid gap-2 text-sm font-medium text-gray-700">Review notes<textarea name="review_notes" rows="3" class="rounded-md border-gray-300"></textarea></label><button class="w-full rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Approve record</button></form>@endcan
            @can('requestCorrection', $record)<form method="POST" action="{{ route('admin.maintenance-reviews.request-correction', $record) }}" class="space-y-3 rounded-md border border-gray-200 bg-white p-4">@csrf<label class="grid gap-2 text-sm font-medium text-gray-700">Correction reason<textarea name="correction_reason" required rows="3" class="rounded-md border-gray-300"></textarea></label><button class="w-full rounded-md bg-amber-600 px-4 py-2 text-sm font-semibold text-white">Request correction</button></form>@endcan
            @can('correct', $record)<a href="{{ route('admin.maintenance-reviews.correction.edit', $record) }}" class="block rounded-md bg-gray-900 px-4 py-2 text-center text-sm font-semibold text-white">Correct record</a>@endcan
            @can('resubmit', $record)<form method="POST" action="{{ route('admin.maintenance-reviews.resubmit', $record) }}">@csrf<button class="w-full rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Resubmit for review</button></form>@endcan
            @can('reject', $record)<form method="POST" action="{{ route('admin.maintenance-reviews.reject', $record) }}" class="space-y-3 rounded-md border border-red-200 bg-white p-4">@csrf<label class="grid gap-2 text-sm font-medium text-gray-700">Rejection reason<textarea name="rejection_reason" required rows="3" class="rounded-md border-gray-300"></textarea></label><button class="w-full rounded-md bg-red-700 px-4 py-2 text-sm font-semibold text-white">Reject record</button></form>@endcan
            @can('reopen', $record)<form method="POST" action="{{ route('admin.maintenance-reviews.reopen', $record) }}" class="space-y-3 rounded-md border border-gray-200 bg-white p-4">@csrf<label class="grid gap-2 text-sm font-medium text-gray-700">Reopen reason<textarea name="reason" required rows="3" class="rounded-md border-gray-300"></textarea></label><button class="w-full rounded-md border border-gray-400 px-4 py-2 text-sm font-semibold text-gray-800">Reopen review</button></form>@endcan
        </aside>
    </div>
</x-app-layout>
