import 'package:flutter/material.dart';
class LoadingPanel extends StatelessWidget{const LoadingPanel({super.key});@override Widget build(BuildContext c)=>const Center(child:Semantics(label:'Loading',child:CircularProgressIndicator()));}
class EmptyPanel extends StatelessWidget{const EmptyPanel(this.message,{super.key});final String message;@override Widget build(BuildContext c)=>Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.inbox_outlined,size:48),const SizedBox(height:12),Text(message,textAlign:TextAlign.center)])));}
class ErrorPanel extends StatelessWidget{const ErrorPanel(this.message,{required this.onRetry,super.key});final String message;final VoidCallback onRetry;@override Widget build(BuildContext c)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.error_outline,size:44),const SizedBox(height:12),Text(message,textAlign:TextAlign.center),const SizedBox(height:16),FilledButton.icon(onPressed:onRetry,icon:const Icon(Icons.refresh),label:const Text('Retry'))])));}
class StatusBadge extends StatelessWidget{const StatusBadge(this.label,{super.key});final String label;@override Widget build(BuildContext c){final text=label.replaceAll('_',' ');return Semantics(label:'Status $text',child:Chip(avatar:const Icon(Icons.circle,size:10),label:Text(text),visualDensity:VisualDensity.compact));}}
class SummaryCard extends StatelessWidget{const SummaryCard({required this.label,required this.value,this.onTap,super.key});final String label;final int value;final VoidCallback? onTap;@override Widget build(BuildContext c)=>Card(child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(8),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:Theme.of(c).textTheme.labelLarge),const SizedBox(height:8),Text('$value',style:Theme.of(c).textTheme.headlineMedium)]))));}
class DetailSection extends StatelessWidget{const DetailSection({required this.title,required this.children,super.key});final String title;final List<Widget> children;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.titleMedium),const Divider(),...children]));}
class LabeledValue extends StatelessWidget{const LabeledValue(this.label,this.value,{super.key});final String label,value;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:120,child:Text(label,style:Theme.of(c).textTheme.labelMedium)),Expanded(child:Text(value))]));}
class PageControls extends StatelessWidget{const PageControls({required this.page,required this.lastPage,required this.onPage,super.key});final int page,lastPage;final ValueChanged<int> onPage;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(16),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton(tooltip:'Previous page',onPressed:page>1?()=>onPage(page-1):null,icon:const Icon(Icons.chevron_left)),Text('Page $page of $lastPage'),IconButton(tooltip:'Next page',onPressed:page<lastPage?()=>onPage(page+1):null,icon:const Icon(Icons.chevron_right))]));}
