<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-medium text-emerald-700">Administration / Users</p><h1 class="text-2xl font-semibold text-gray-900">{{ $user?'Edit user':'Add user' }}</h1></div></x-slot>
    <div class="mx-auto max-w-4xl space-y-5">@include('admin.partials.tabs')<form method="POST" action="{{ $user?route('admin.users.update',$user):route('admin.users.store') }}" class="space-y-6 rounded-md border border-gray-200 bg-white p-6">@csrf @if($user)@method('PUT')@endif
        <div class="grid gap-5 sm:grid-cols-2">@foreach(['first_name'=>'First name','middle_name'=>'Middle name','last_name'=>'Last name','suffix'=>'Suffix','email'=>'Email','username'=>'Username','employee_no'=>'Employee number','student_no'=>'Student number','mobile_number'=>'Mobile number'] as $name=>$label)<div><label for="{{ $name }}" class="mb-1 block text-sm font-medium text-gray-700">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" type="{{ $name==='email'?'email':'text' }}" value="{{ old($name,$user?->{$name}) }}" class="w-full rounded-md border-gray-300 text-sm">@error($name)<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach</div>
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="password" class="mb-1 block text-sm font-medium text-gray-700">Password {{ $user?'(leave blank to keep current)':'' }}</label><input id="password" type="password" name="password" class="w-full rounded-md border-gray-300 text-sm">@error('password')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="password_confirmation" class="mb-1 block text-sm font-medium text-gray-700">Confirm password</label><input id="password_confirmation" type="password" name="password_confirmation" class="w-full rounded-md border-gray-300 text-sm"></div></div>
        <input type="hidden" name="roles_present" value="1"><fieldset><legend class="mb-3 text-sm font-semibold text-gray-900">Roles</legend><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($roles as $role)<label class="flex items-center gap-2 rounded-md border border-gray-200 px-3 py-2 text-sm"><input type="checkbox" name="roles[]" value="{{ $role->name }}" @checked(in_array($role->name,old('roles',$user?->roles->pluck('name')->all()??[]),true)) class="rounded border-gray-300 text-emerald-700">{{ $role->name }}</label>@endforeach</div></fieldset>
        <input type="hidden" name="is_active" value="0"><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="is_active" value="1" @checked((bool)old('is_active',$user?->is_active??true)) class="rounded border-gray-300 text-emerald-700">Active account</label>
        <div class="flex justify-end gap-3 border-t border-gray-200 pt-5"><a href="{{ route('admin.users.index') }}" class="px-3 py-2 text-sm font-semibold text-gray-600">Cancel</a><button class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">{{ $user?'Save changes':'Create user' }}</button></div>
    </form></div>
</x-app-layout>
