<x-app-layout>
    <x-slot name="header"><div class="flex w-full items-center justify-between gap-4"><div><p class="text-sm font-medium text-emerald-700">Administration / Users</p><h1 class="text-2xl font-semibold text-gray-900">User accounts</h1></div><a href="{{ route('admin.users.create') }}" class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Add user</a></div></x-slot>
    <div class="space-y-5">@if(session('success'))<div class="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif @include('admin.partials.tabs')
        <form method="GET" class="grid gap-3 border-b border-gray-200 pb-5 sm:grid-cols-2 xl:grid-cols-[1fr_11rem_10rem_11rem_9rem_auto]">
            <input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search users" class="rounded-md border-gray-300 text-sm" aria-label="Search users">
            <select name="role" class="rounded-md border-gray-300 text-sm" aria-label="Role filter"><option value="">All roles</option>@foreach($roles as $role)<option value="{{ $role->name }}" @selected(($filters['role'] ?? '')===$role->name)>{{ $role->name }}</option>@endforeach</select>
            <select name="status" class="rounded-md border-gray-300 text-sm" aria-label="Status filter"><option value="">All statuses</option><option value="active" @selected(($filters['status'] ?? '')==='active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '')==='inactive')>Inactive</option></select>
            <select name="sort" class="rounded-md border-gray-300 text-sm" aria-label="Sort users"><option value="created_at">Newest</option><option value="name" @selected(($filters['sort'] ?? '')==='name')>Name</option><option value="email" @selected(($filters['sort'] ?? '')==='email')>Email</option><option value="is_active" @selected(($filters['sort'] ?? '')==='is_active')>Status</option></select>
            <select name="per_page" class="rounded-md border-gray-300 text-sm" aria-label="Rows per page">@foreach([10,15,25,50] as $n)<option value="{{ $n }}" @selected((int)($filters['per_page']??15)===$n)>{{ $n }} rows</option>@endforeach</select><button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Apply</button>
        </form>
        <div class="flex justify-between"><p class="text-sm text-gray-500">{{ $users->total() }} accounts</p><a href="{{ route('admin.users.export', request()->query()) }}" class="text-sm font-semibold text-gray-700 hover:text-emerald-700">Export CSV</a></div>
        <div class="overflow-hidden rounded-md border border-gray-200 bg-white"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">User</th><th class="px-4 py-3 text-left">Identifiers</th><th class="px-4 py-3 text-left">Roles</th><th class="px-4 py-3 text-left">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-gray-100">
            @forelse($users as $user)<tr class="hover:bg-gray-50"><td class="px-4 py-3"><p class="font-semibold text-gray-900">{{ $user->name }}</p><p class="text-gray-500">{{ $user->email }}</p></td><td class="px-4 py-3 text-gray-600">{{ $user->employee_no ?: $user->student_no ?: '—' }}</td><td class="px-4 py-3 text-gray-600">{{ $user->roles->pluck('name')->implode(', ') ?: 'No role' }}</td><td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $user->is_active?'bg-emerald-50 text-emerald-700':'bg-gray-100 text-gray-600' }}">{{ $user->is_active?'Active':'Inactive' }}</span></td><td class="px-4 py-3 text-right"><a href="{{ route('admin.users.show',$user) }}" class="font-medium text-gray-600">View</a><a href="{{ route('admin.users.edit',$user) }}" class="ml-3 font-medium text-emerald-700">Edit</a></td></tr>
            @empty<tr><td colspan="5" class="px-4 py-12 text-center text-gray-500">No user accounts match the current filters.</td></tr>@endforelse
        </tbody></table></div></div>{{ $users->links() }}
    </div>
</x-app-layout>
