<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-medium text-emerald-700">Administration / Assets</p><h1 class="text-2xl font-semibold text-gray-900">{{ $record ? 'Edit maintenance record' : 'Record maintenance completion' }}</h1></div></x-slot>
    <form method="POST" action="{{ $record ? route('admin.asset-maintenance.update', $record) : route('admin.asset-maintenance.store') }}" class="space-y-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
        @csrf
        @if($record) @method('PUT') @endif
        <div class="grid gap-5 md:grid-cols-2">
            <label class="grid gap-2 text-sm font-medium text-gray-700">Asset<select name="asset_id" required class="rounded-md border-gray-300 text-sm"><option value="">Select asset</option>@foreach($assets as $asset)<option value="{{ $asset->id }}" @selected((string)old('asset_id', $record?->asset_id ?? request('asset_id')) === (string)$asset->id)>{{ $asset->asset_tag }} - {{ $asset->name }}</option>@endforeach</select>@error('asset_id')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Maintenance type<select name="maintenance_type_id" class="rounded-md border-gray-300 text-sm"><option value="">Not specified</option>@foreach($maintenanceTypes as $type)<option value="{{ $type->id }}" @selected((string)old('maintenance_type_id', $record?->maintenance_type_id) === (string)$type->id)>{{ $type->name }}</option>@endforeach</select></label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Completion date<input type="date" name="completion_date" value="{{ old('completion_date', $record?->completion_date?->toDateString() ?? now()->toDateString()) }}" required class="rounded-md border-gray-300 text-sm">@error('completion_date')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Performed by<input name="performed_by" value="{{ old('performed_by', $record?->performed_by) }}" placeholder="External technician or team" class="rounded-md border-gray-300 text-sm"></label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Preventive schedule<select name="maintenance_schedule_id" class="rounded-md border-gray-300 text-sm"><option value="">Manual or unscheduled</option>@foreach($schedules as $schedule)<option value="{{ $schedule->id }}" @selected((string)old('maintenance_schedule_id', $record?->maintenance_schedule_id ?? request('maintenance_schedule_id')) === (string)$schedule->id)>{{ $schedule->title }} / {{ $schedule->asset?->asset_tag }}</option>@endforeach</select>@error('maintenance_schedule_id')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Work order<select name="work_order_id" class="rounded-md border-gray-300 text-sm"><option value="">No linked work order</option>@foreach($workOrders as $workOrder)<option value="{{ $workOrder->id }}" @selected((string)old('work_order_id', $record?->work_order_id) === (string)$workOrder->id)>{{ $workOrder->work_order_number }} - {{ $workOrder->title }}</option>@endforeach</select>@error('work_order_id')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Technician / staff<select name="staff_profile_id" class="rounded-md border-gray-300 text-sm"><option value="">Not assigned</option>@foreach($staff as $person)<option value="{{ $person->id }}" @selected((string)old('staff_profile_id', $record?->staff_profile_id) === (string)$person->id)>{{ $person->user?->name ?? $person->employee_code }}</option>@endforeach</select>@error('staff_profile_id')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Labor cost<input type="number" step="0.01" min="0" name="labor_cost" value="{{ old('labor_cost', $record?->labor_cost) }}" class="rounded-md border-gray-300 text-sm">@error('labor_cost')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Total cost<input type="number" step="0.01" min="0" name="total_cost" value="{{ old('total_cost', $record?->total_cost) }}" class="rounded-md border-gray-300 text-sm"></label>
            <label class="grid gap-2 text-sm font-medium text-gray-700">Next maintenance date<input type="date" name="next_maintenance_date" value="{{ old('next_maintenance_date', $record?->next_maintenance_date?->toDateString()) }}" class="rounded-md border-gray-300 text-sm"></label>
        </div>
        <label class="grid gap-2 text-sm font-medium text-gray-700">Findings<textarea name="findings" rows="4" class="rounded-md border-gray-300 text-sm">{{ old('findings', $record?->findings) }}</textarea>@error('findings')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-2 text-sm font-medium text-gray-700">Actions taken<textarea name="actions_taken" rows="5" required class="rounded-md border-gray-300 text-sm">{{ old('actions_taken', $record?->actions_taken) }}</textarea>@error('actions_taken')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
        <label class="grid gap-2 text-sm font-medium text-gray-700">Remarks<textarea name="remarks" rows="3" class="rounded-md border-gray-300 text-sm">{{ old('remarks', $record?->remarks) }}</textarea>@error('remarks')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
        <div class="flex justify-end gap-3"><a href="{{ route('admin.asset-maintenance.index') }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Cancel</a><button class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Save completion</button></div>
    </form>
</x-app-layout>
